version: '3.8'

services:
  dyncfdns:
    image: alxdroiddev/dyncfdns:latest
    container_name: dyncfdns
    hostname: dyncfdns
    restart: unless-stopped
    expose:
      - 5000
    ports:
      - 5000:5000 # Map the API port to the host
    environment:
      - HOST_LIST=home.example.com,server.example.com
      - CLOUDFLARE_API_TOKEN=your_api_token
      - CLOUDFLARE_API_KEY=your_api_key
      - CLOUDFLARE_API_EMAIL=your-email@example.com
      - UPDATE_INTERVAL=120  # OPTIONAL - Update interval in seconds (default is 120 seconds)
      - ALLOW_CREATE_HOSTS=false # OPTIONAL - Set to true if you want to allow creating new hosts via the API
      - API_PORT=5000 # OPTIONAL - Port for the API (default is 5000)
    volumes:
      - logs:/app/logs # OPTIONAL: Mount a volume for logs and previous IP file
                       #           if this volume is not set, DynCFDNS will always set the
                       #           current IP as the external IP, regardless of the previous IP
                      #            Make sure the folder is writeable by the container
    # optional: use .env file instead of environment variables
    env_file:
      - path: ./.env
        required: false
    deploy:
      resources:
        limits: # hard limit
          cpus: '0.1'
          memory: 64M
        reservations: # soft reservation
          cpus: '0.01'
          memory: 32M


volumes:
  logs: